# Site settings 配置站点
title: '以太经典ETC中文网'
description: '介绍以太经典ETC的最新资讯，包括技术，团队和社区，为大家呈现最全面的Ethereum_Classic'
keyword: '以太经典ETC,技术进度,项目进展,中国社区,国际社区,核心开发团队'
url: 'http://ethereumclassic.cn' # your host
sponsor: 哥德尔实验室Gödel Labs
sponsorContact: Contact@godel.ai


# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  首页: '/'
  资源: '/resource.html'
  #资讯: '/tags.html'

miss:
  home: '/'

# Footer
footer:
  since: ETCChina

# Author 配置博主信息
author: 'Yan'
nickname: 'Gödel Labs'
bio: '  哥德尔实验室Gödel Labs是区块链Blockchain&人工智能AI技术研究与开发公司，由区块链技术工程师、密码学家、数学家与AI研究学者共同发起成立。宗旨是通过创建去中心化系统，建立一个自由、公平和开放的数字社会。'
avatar: '//image.ibb.co/k5h3bV/goedel-labs-gaitubao-com-231x249-gaitubao-com-187x202.jpg'

# Search
search: true

# Night mode
nightMode: true

# Comments 评论功能
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'

#intensedebate 评论功能
intensedebate_comments: false

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'twitter', 'facebook']
social-title: 分享文章：
#social-share-items: ['wechat', 'weibo', 'twitter', 'facebook', 'telegram']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'seaOfClouds'

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  weibo: '//weibo.com/6426321445/profile?topnav=1&wvr=6&is_all=1'
  linkedin: '//cn.linkedin.com/company/goedel?trk=ppro_cprof'


#webchat: '//image.ibb.co/mBaQuK/1538299208.png'

#jianshu: '//www.jianshu.com/u/11c1ad5e8788'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 100
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

#sass file
sass:
    style: compressed

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]
